version : '3'

services:
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: msbatista
      ME_CONFIG_BASICAUTH_PASSWORD: 12345!!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: msbatista
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345!!
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: msbatista
      MONGO_INITDB_ROOT_PASSWORD: 12345!!
    ports:
      - "27017:27017"
    volumes:
      - ${HOME}/.dev/docker/volumes/mongodb:/data/db
    networks:
      - mongo-compose-network
  neo4j:
    container_name: neo4j-sna
    image: neo4j:latest
    volumes:
      - ${HOME}/.dev/neo4j/conf:/conf
      - ${HOME}/.dev/neo4j/logs:/logs
      - ${HOME}/.dev/neo4j/data:/data
      - ${HOME}/.dev/neo4j/plugins:/plugins
      - ${HOME}/.dev/neo4j/import:/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/connect
      NEO4J_dbms_logs_debug_level: DEBUG
      NEO4J_dbms_memory_heap_max__size: 4G
      NEO4J_dbms_memory_pagecache_size: 1G

networks:
  mongo-compose-network:
    driver: bridge